---
# This Docker composition file is used to build and test the container

name: gatherer

secrets:
  database_creds:
    file: ./src/secrets/database_creds.yml

services:
  gatherer:
    # Run the container normally
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    image: cisagov/gatherer
    init: true
    restart: "no"
    secrets:
      - source: database_creds
        target: database_creds.yml
  redis:
    image: redis:alpine
