version: '3.2'

secrets:
  database_creds:
    file: ./secrets/database_creds.yml

services:
  gatherer:
    build: .
    image: 'dhub.ncats.dhs.gov:5001/gatherer:latest'
    secrets:
      - source: database_creds
        target: database_creds.yml
