---
version: "3.7"

# This Docker composition file is used to build and test the container

secrets:
  database_creds:
    file: ./src/secrets/database_creds.yml

services:
  gatherer:
    # Run the container normally
    build:
      # VERSION must be specified on the command line:
      # e.g., --build-arg VERSION=0.0.1
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    image: cisagov/gatherer
    init: true
    restart: "no"
<<<<<<< HEAD
=======
    environment:
      - ECHO_MESSAGE=Hello World from docker compose!
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
>>>>>>> 9cea64da4a1379cdde3c509a09fc548f0da8b034
    secrets:
      - source: database_creds
        target: database_creds.yml
  redis:
    image: redis:alpine
